168 user has infiltration rasters defined but no simple infiltration referral in the global settings
nens/threedi-modelchecker pull request #284
Opened 2023-03-01 09:32 UTC by elisallenens

If a record in the v2_simple_infiltration table exists but is not referenced from v2_global_settings, this gives an info message notifying the user.

2023-03-02 08:21 UTC, caspervdw requested changes
One minor remark, and can you also add checks for the other settings tables listed in the issue?

2023-03-02 08:21 UTC, caspervdw commented on threedi_modelchecker/config.py
> +            == models.GlobalSetting.simple_infiltration_settings_id,
This is now comparing against *all* global settings, while we only use the *first* global settings record. So you'll need to compare the `SimpleInfiltration.id` with a scalar subquery (defined above as `first_setting` or something like that)

2023-03-03 10:49 UTC, elisallenens commented
Should the check also run for v2_global_settings.control_group_id?

2023-03-03 11:17 UTC, caspervdw commented
I don’t know how control groups work, maybe @jpprins1 can help

2023-03-03 13:22 UTC, caspervdw requested changes
Looks good now! Only one thing: it should be a INFO, not ERROR (the default), see issue description.

2023-03-06 08:20 UTC, elisallenens commented
oops

2023-03-06 08:30 UTC, caspervdw approved these changes

2023-03-06 08:30 UTC, merged