WIP
nens/threedi-modelchecker pull request #55
Opened 2021-03-15 10:06 UTC by caspervdw

2021-03-16 09:47 UTC, jpprins1 commented
I don't see a problem in making `alembic` a requirement. You don't need the migrations for reading the SQLite and validation, but it's so close related that splitting this stuff up in multiple Pypi packages (pluging style or not) does not make much sense to me.

2021-03-16 10:07 UTC, jpprins1 requested changes
Looks good, some small remarks/questions to look at. Can be merged afterwards!

2021-03-16 10:07 UTC, jpprins1 commented on threedi_modelchecker/threedi_model/constants.py
> +#  Migration 174 deletes some fields, which were already not present in the
Good, we need a Django migration worker (for a period of time) to get to migration 174 for users that have schematisations with older migrations. Think we can add a better (error) message with instructions what to do in the functions/libs that are going to be build upon this lib.

2021-03-18 16:16 UTC, caspervdw commented on setup.py
> +    "alembic>=0.9",
It is not customary to do so. Only in the case that you know it is going to fail with some version, you could exclude it. But we test against all newest versions so there is no reason to do that.

2021-03-18 16:31 UTC, caspervdw commented on threedi_modelchecker/schema.py
> +
I thought it would be a good idea to also be able to "upgrade" a completely empty database. In that case, version is None.

2021-03-30 09:02 UTC, jpprins1 approved these changes

2021-03-30 09:38 UTC, merged